### ISSUE TITLE
Android Pay: Throws exception when trying to reuse card

### ISSUE THREAD

**Issue by shewu** [googlesamples/io2015-codelabs#12]
Exception trace:

```
05-29 10:44:22.168  21772-21772/com.yourmom.androidpay E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.yourmom.androidpay, PID: 21772
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=889, result=-1, data=Intent { (has extras) }} to activity {com.yourmom.androidpay/com.yourmom.androidpay.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.wallet.ProxyCard com.google.android.gms.wallet.FullWallet.getProxyCard()' on a null object reference
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.wallet.ProxyCard com.google.android.gms.wallet.FullWallet.getProxyCard()' on a null object reference
            at com.yourmom.androidpay.MainActivity.onActivityResult(MainActivity.java:119)
            at android.app.Activity.dispatchActivityResult(Activity.java:6192)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by shewu** [comment]
Here is a simple fix. We can just disable the `Confirm` button until we get a valid token, and then disable the button again after we have successfully used the token.

```
codelab-6:~ codelab$ diff /Users/codelab/Desktop/activity_main.xml /Users/codelab/AndroidStudioProjects/AndroidPay/app/src/main/res/layout/activity_main.xml 
16a17
>         android:id="@+id/confirm_button"
20a22
>         android:enabled="false"
codelab-6:~ codelab$ diff /Users/codelab/Desktop/MainActivity.java /Users/codelab/AndroidStudioProjects/AndroidPay/app/src/main/java/com/yourmom/androidpay/MainActivity.java 
104a105
>                         ((Button)findViewById(R.id.confirm_button)).setEnabled(true);
125a127
>                         ((Button)findViewById(R.id.confirm_button)).setEnabled(false);
```

**Comment by samtstern** [comment]
Will fix this during the next codelab update.
