### ISSUE TITLE
Run time error when starting app - Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by ajaybarvey** [googlesamples/io2015-codelabs#81]
05-30 01:39:22.251 5922-5922/com.example.android.voicecamera D/CameraActivity: onCreate: 
05-30 01:39:22.254 5922-5922/com.example.android.voicecamera D/AndroidRuntime: Shutting down VM
05-30 01:39:22.264 5922-5922/com.example.android.voicecamera E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.android.voicecamera, PID: 5922
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.voicecamera/com.example.android.voicecamera.CameraActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.GoogleCamera }
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5351)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                                                Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.google.android.GoogleCamera }
                                                                                   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
                                                                                   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
                                                                                   at android.app.Activity.startActivityForResult(Activity.java:3823)
                                                                                   at android.app.Activity.startActivityForResult(Activity.java:3784)
                                                                                   at android.app.Activity.startActivity(Activity.java:4094)
                                                                                   at android.app.Activity.startActivity(Activity.java:4062)
                                                                                   at com.example.android.voicecamera.CameraActivity.onCreate(CameraActivity.java:38)
                                                                                   at android.app.Activity.performCreate(Activity.java:6020)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5351) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by issamux** [comment]
Hi,
I don't know if this is the best way to do it but this solve my problem;
1. First download this [android sample project](https://developer.android.com/samples/Camera2Basic/project.html)
2. make CameraActivity as exported android:exported="true" and run app. (maybe if you have already an installed camera application and u know the package name you can use it, without installing this sample app..). 
   3.Next in Voice project , replace :
   `intent.setPackage("com.google.android.GoogleCamera");`
   By
   `intent.setClassName("com.example.android.camera2basic","com.example.android.camera2basic.CameraActivity");`

Now u can start voice-interaction project, Camera will ask for permission and then click Home, and continue tutorial :
- Openthe Google app.
- Say “OK Google”.
- When the voice prompt appears, say “Take a selfie”.
- Answer “cheese”.
